<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="fc_DEG" Id="{0c0f8bac-048c-4af1-a933-f23836f12c0a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION fc_DEG : real
VAR_INPUT
		rad : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fc_DEG := fc_MODR(57.29577951308232 * RAD, 360.0);]]></ST>
    </Implementation>
    <LineIds Name="fc_DEG">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>